<?php

namespace App\Filament\Resources\Reports\Tables;

use App\Filament\Support\TableFilters;
use App\Models\Reports;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Table;

class ReportsTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('no')
                    ->label('#')
                    ->rowIndex(),
                TextColumn::make('report_id')
                    ->searchable(),
                TextColumn::make('report_type')
                    ->searchable(),
                TextColumn::make('generated_by')
                    ->searchable(),
                TextColumn::make('generated_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('format')
                    ->badge(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                TableFilters::distinct('report_type', Reports::class, 'Report Type'),
                TableFilters::distinct('generated_by', Reports::class, 'Generated By'),
                TableFilters::select('format', [
                    'pdf' => 'Pdf',
                    'excel' => 'Excel',
                    'csv' => 'Csv',
                ]),
                TableFilters::dateRange('generated_at', 'Generated Date'),
                TableFilters::createdAt(),
            ], layout: FiltersLayout::AboveContentCollapsible)
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
